### ISSUE TITLE
Blood Magic in 1.12.2

### ISSUE THREAD

**Issue by afontaine** [Soartex-Modded/Modded-1.12.x#10]
Blood magic was ported to 1.12, but I'm not sure if there have been any real changes to the mod since 1.10. The textures can maybe be directly ported from 1.10 to 1.12 then? I'm not very knowledgable about building these packs.

**Comment by Shoeboxam** [comment]
Blood magic has been ported. If there are still missing textures, we're welcoming PR's or .zips!
