### ISSUE TITLE
Quark iconmap needs updating/removal

### ISSUE THREAD

**Issue by Dead2** [Soartex-Modded/Modded-1.12.x#14]
Currently several icons are missing entirely from the soartex version, making for example the quark settings page impossible to use because there is no way to see what options are enabled or disabled.

To me it looks like nothing has been changed from the old original, so just removing this file from soartex would be a quick and easy improvement.

See:
https://github.com/Vazkii/Quark/blob/master/src/main/resources/assets/quark/textures/misc/general_icons.png

**Comment by zISKo666** [comment]
I made a quick update.

Thank you for reporting.
