### ISSUE TITLE
Missing Textures Biomes O' Plenty

### ISSUE THREAD

**Issue by judicius** [Soartex-Modded/Modded-1.12.x#26]
There are a few missing textures in BoP from things that have been added. Is there any plan to update these missing textures? If someone is willing to do the textures I can create a comprehensive list of what is currently missing.

**Comment by leagris** [comment]
Probably yes. If you feel like contributing some of these, all help is appreciated. Soartex Modded is a community work.

**Comment by Eleiyas** [comment]
> Probably yes. If you feel like contributing some of these, all help is appreciated. Soartex Modded is a community work.

Hi there Lea, is there a chance that my pull request from 2 months ago can get a look at soon?
I still have many many other textures to add in, but the other person who is semi-online here said to do my pull requests on a "per mod" basis.
