### ISSUE TITLE
chisel ctm not working

### ISSUE THREAD

**Issue by robjw95** [Soartex-Modded/Modded-1.12.x#29]
after recent mod updates the ctm textures are not working

![67143018-fbe7bb80-f234-11e9-8af1-a61847947faa](https://user-images.githubusercontent.com/29755733/67151931-af839680-f29b-11e9-80f9-5df5d8afcd8e.png)

![67143022-06a25080-f235-11e9-820d-bacf05ad3a9f](https://user-images.githubusercontent.com/29755733/67151933-b1e5f080-f29b-11e9-8dae-47ce3cdeed44.png)

mod author says "The resource pack needs to be updated to include the .mcmeta files for the textures it's overriding, Minecraft won't load .mcmeta files from other resource packs (in this case Chisel's)."

**Comment by tterrag1098** [comment]
To quote [the wiki](https://minecraft.gamepedia.com/Resource_pack#Animation):

> If the .mcmeta file does not exist in the pack and the texture does, the game will assume the texture is not animated, rather than loading a .mcmeta file from a pack below that pack.

The same applies to ctm data as it does to animation data.

**Comment by artdude543** [comment]
Hmm we've never had this issue before. Even with other mods with CTM support.

Will be back-logged till someone is free to further debug and look into a fix.

**Comment by tterrag1098** [comment]
Those other mods were using the old system then. This is unfortunately just how mcmeta files work, it would be the same if you changed a texture with an animation, you have to copy over the animation data, yes?

**Comment by artdude543** [comment]
Resolved with https://github.com/Soartex-Modded/Modded-1.12.x/commit/6f9744f3407958d3d23520461894e26912067bf4
