### ISSUE TITLE
Applied Energistics 2 - ME Glass Cable texture missing

### ISSUE THREAD

**Issue by fuwwy** [Soartex-Modded/Modded-1.12.x#37]
The texture for AE2's ME Glass Cable seems to be missing.
![image](https://user-images.githubusercontent.com/9268058/78070629-084f7300-7394-11ea-8efb-76c6a2471d8e.png)

**Comment by Ommina** [comment]
You seem to have a texture pack loaded - Soartex, unless I'm very much mistaken.  Does this persist using AE2 textures?

**Comment by Eleiyas** [comment]
> You seem to have a texture pack loaded - Soartex, unless I'm very much mistaken. Does this persist using AE2 textures?

This is the Soartex GitHub, so the issue is that the texture isn't loading when using Soartex.

I'll see if I can replicate the bug on my own version later.

**Comment by Eleiyas** [comment]
Sorry, the Glass Fibre - Fluix shows up perfectly fine in my game :/

**Comment by fuwwy** [comment]
> Sorry, the Glass Fibre - Fluix shows up perfectly fine in my game :/

It shows fine while alone but disappears when in a corner or connected to a bus

**Comment by Sgregory42** [comment]
Hey got the same issue, any workaround idea ? Thanks

**Comment by ScottKillen** [comment]
Do you have any other resource packs installed, and if so, please list them. I think this is a case where Soartex is relying on some default model and/or blockstate files that are being overwritten by the other pack.

**Comment by zISKo666** [comment]
Hi,

I've tried to replicate this issue but in all my tests things are looking fine.
From my POV this is not an Soartex issue.
My guess is that there is an issue with one of your mods.

Below is my replication of the scenery ( w/o the skull in the bush :) ) ...
![2020-04-25_12 46 07](https://user-images.githubusercontent.com/6992216/80277982-11153980-86f3-11ea-9e64-4a897bf0de4b.png)

**Comment by Ommina** [comment]
> This is the Soartex GitHub, so the issue is that the texture isn't loading when using Soartex.

Oops.  Well, that's rather embarrassing.  I did somewhat wonder at the time when the AE2 project got all these new members.  /cough
