### ISSUE TITLE
Applied Energistics 2 - animation speed

### ISSUE THREAD

**Issue by ExDotRS** [Soartex-Modded/Modded-1.12.x#39]
The cycle for the ME-controller is set to 1 frame per second, instead of 1 per 3 ticks like for the molecular assembler. Feature or oversight?

**Comment by Eleiyas** [comment]
I like it how it is *shrug* - probably no one noticed :p

**Comment by artdude543** [comment]
The slow colour changing is intentional for the block. We didn't like it changing quickly, and adds to the looks for base designs which use them for flooring.
________________________________
