### ISSUE TITLE
Xnet texture same as Twilight forest

### ISSUE THREAD

**Issue by Protheus** [Soartex-Modded/Modded-1.12.x#4]
The Xnet textures is using Twilight forest textures

**Comment by artdude543** [comment]
Huh never noticed that in the PR from @Darkosto will get it sorted sometime next week. (We have a large update/change coming)

**Comment by artdude543** [comment]
This has been fixed in https://github.com/Soartex-Modded/Modded-1.12.x/commit/fe87b4322c743ec79083a1d576a08a4c47bf6643 :)
