### ISSUE TITLE
[Request] EnderIO missing

### ISSUE THREAD

**Issue by cap1o** [Soartex-Modded/Modded-1.12.x#40]
Hello,

I tried to find out where i can post a request but i have found only Github so far.
I would like to ask Soartex to add the EnderIO mod at the universal mod resource pack 1.12 please.
Most of Textures were on the resource pack before 1.12.
Thank you !

**Comment by Shoeboxam** [comment]
I added this request to a centralized issue for mod requests. Some Ender IO textures have been ported now. Welcoming additional PR's or .zips.
