### ISSUE TITLE
[Update Request]Botania textures for 1.12

### ISSUE THREAD

**Issue by H1de0nbush** [Soartex-Modded/Modded-1.12.x#41]
After looking in Soartex-Modded/Modded-1.11.x/Botania , I found that in 1.12 Botania changes most of the names of the textures of blocks and items.
Such as:
manasteel.png -> manasteel_ingot.png
manasteelnugget.png -> manasteel_nugget.png
...
Hope that one day Soartex can update the support of Botania in 1.12 .
Love this texture pack.

**Comment by Eleiyas** [comment]
I've already done all this, it's a very simple fix.
I still need to add merge requests for about 6 different mods.

**Comment by Shoeboxam** [comment]
I ported Botania here:
https://github.com/Soartex-Modded/Modded-1.12.x/pull/43

If there are other mods missing ports, please open another issue. After the above PR, there should be fewer missing ports.
