### ISSUE TITLE
Bauxite ore is FULL PURPLE

### ISSUE THREAD

**Issue by Bajosi** [Soartex-Modded/Modded-1.12.x#5]

**Comment by artdude543** [comment]
Can you please give more detail and a screenshot of the issue your having? Thanks.

**Comment by Bajosi** [comment]
![2018-02-18_20 41 08](https://user-images.githubusercontent.com/36478306/36355458-7ec3d252-14f4-11e8-86bb-09d1ff18e81d.png)
I Look resourcepack's in and i couldnt see anything about these pink blocks.

**Comment by artdude543** [comment]
Am I assuming you have downloaded directly from this repo? If so it won't work as you need an addon pack which contains the ores/ingots etc... it's still WIP hence why no release on the site or GitHub. The last download we made is working, however. But it outdated to the repo.

**Comment by artdude543** [comment]
It's also not a missing texture; as a missing texture is pink and black squares. So you either have a mod changing how something is working or have a broken mod/RP. But from what I can tell it's not the RP at fault here as I can't reproduce on my testing modpack. Which has IE and its textures are loading fine.

**Comment by Bajosi** [comment]
if i add different texture for these can it work normally? (maybe soartex-ores)

**Comment by artdude543** [comment]
You can add that on top for sure; as that's the missing one. But I don't recommend using it as a permanent solution as it's still in testing and still has missing textures. If you want to use something stable you'll have to wait for the main release from us. Which we don't have an ETA currently. So you could be waiting a while.

**Comment by Bajosi** [comment]
anyway ty

**Comment by artdude543** [comment]
If you were wanting something that Darkosto has. That is a private testing version he is running to help me with the porting/fixing of textures. Which none of textures/models is on any of the repos publically.

**Comment by Bajosi** [comment]
if i dont wrong, i fixed the problem with deleting blockstates and models
