### ISSUE TITLE
Thermal foundation metallic ores miss textures.

### ISSUE THREAD

**Issue by EnoralTheOutCast** [Soartex-Modded/Modded-1.12.x#53]
By Metallic ores i mean Copper, tin, silver, aluminum, lead, platinum, nickel, iridium and mana infused.
All have missing textures
![2023-06-14_18 56 06](https://github.com/Soartex-Modded/Modded-1.12.x/assets/67475809/a15b3a18-e2bc-4716-bcbb-4f64c2fa7fff)
Like, this is aluminum for example.

**Comment by EnoralTheOutCast** [comment]
and i have checked the base repo, you have those there

**Comment by ScottDTA** [comment]
I'll get these fixed in the repo.  Not sure when we will get another release pushed out.

**Comment by EnoralTheOutCast** [comment]
Great, thank you.

**Comment by ScottDTA** [comment]
This was fixed in commit 736a4f4
