### ISSUE TITLE
Chisel texture naming

### ISSUE THREAD

**Issue by zISKo666** [Soartex-Modded/Modded-1.12.x#8]
Some of the Chisel textures are with upper case letters.

* Chisel\assets\chisel\textures\blocks\technical *

I've tried to change them to lower case but my GitHub Desktop seams not to recognize the name changes.
Any idea?
Or someone might be help changing them?

**Comment by artdude543** [comment]
There was a way to force the changes to be seen but I can't remember at the moment (and in transit xD). Alt method would be to purge the entire folder commit then copy back over the fixed naming then commit again.

**Comment by ScottKillen** [comment]
See this article on the subject: [How do I commit case-sensitive only filename changes in Git?](https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by leagris** [comment]
Try this one in a Linux/OSX environment:

https://github.com/Soartex-Modded/Modded-1.12.x/tree/lowercase-chisel/Chisel

**Comment by zISKo666** [comment]
Finally I solved this issue.

Thanx for your help.
